#ifndef __STREAMDEF_H__
#define __STREAMDEF_H__


#define SVS_STREAM_SERVICE_NAME  "svs_mu_adapter"


#define SVS_STREAM_CONFIG_PATH  "../conf/"


#define SVS_STREAM_CONFIG_FILE   "../conf/svs_mu_stream.conf"


#define SVS_STREAM_LOG_PATH      "../log/svs_mu_stream.log"


#define SVS_STREAM_LOG_DIR       "../log/"


#define STREAM_MAX_QUEUE_DELAY       (100 * 1000)


#define STREAM_MAX_EPOLL_SIZE        (10000)


#define STREAM_MAX_TIME_PER_THREAD   (500 * 1000)


#define STREAM_BUSINESS_REPORT_INTERVAL  10

#define KILO    (1024)


#define BYTE_NUM  (8)

#define STREAM_MAX_COPY_STREAM_NUM    100

enum _enSTREAM_MSG_BLOCK_DEF
{
    STREAM_MSG_BLOCK_SIZE          = 2 * 1024,
    STREAM_SVS_BLOCK_SIZE          = 1800,
    STREAM_BLOCK_NUM_PER_CHANNEL   = 400,
    STREAM_MAX_QUEUE_MSG_NUM       = 1 * 1024,
    STREAM_MAX_QUEUE_BYTE_SIZE     = (STREAM_MSG_BLOCK_SIZE * STREAM_MAX_QUEUE_MSG_NUM),
    MAX_PACKET_NUM_PER_FRAME    = 1024,
    MAX_TRACKINFO_PACKET_NUM    = 50,
    MAX_TRACKINFO_PACKET_SIZE   = 1024
};


enum _enSTREAM_THREAD_NUM
{
    STREAM_EXCHANGE_THREAD_NUM     = 8,
    STREAM_MEDIA_RECV_THREAD_NUM   = 4
};

enum _enSTREAM_TIME_DEFINE
{
    STREAM_CONFIG_RELOAD_INTERVAL          = 60,
    STREAM_STATUS_CHECK_INTERVAL           = 5,
    STREAM_STATUS_TIMEOUT_INTERVAL         = 30,
    STREAM_STATUS_ABNORMAL_INTERVAL        = 10,
    STREAM_CONNECT_ABNORMAL_INTERVAL       = 30,

    STREAM_MEDIA_CHANNEL_HEARTBEAT_INTERVAL = 15,
    STREAM_MEDIA_CHANNEL_INVAILD_INTERVAL  = 4 * 15

};


#endif
