#ifndef _SVS_RC_H
#define _SVS_RC_H

enum SVS_SS_RESPCODE
{
    SVS_RESPCODE_SUCCESS               =  0,
    SVS_RESPCODE_NOT_TRANSFER          =  1,
    SVS_RESPCODE_DB_ERROR              =  2,
    SVS_RESPCODE_MEM_ERROR             =  3,
    SVS_RESPCODE_FILE_ERROR            =  4,
    SVS_RESPCODE_NO_FRONTSVR           =  5,
    SVS_RESPCODE_NO_FRONTDEV           =  6,
    SVS_RESPCODE_NO_FILE               =  7,
    SVS_RESPCODE_ROUTER_EXISTED        =  8,
    SVS_RESPCODE_NOT_REACH_STORESVR    =  9,
    SVS_RESPCODE_NO_CENTERSVR          = 10,
    SVS_RESPCODE_NO_VTDU               = 11,
    SVS_RESPCODE_NEED_DEVICEID         = 12,
    SVS_RESPCODE_ILLEGA_CONDITION      = 13,
    SVS_RESPCODE_NEDD_TIME_SLICE       = 14,
    SVS_RESPCODE_NO_STRATEGY           = 15,
    SVS_RESPCODE_ILLEGA_USER           = 16,
    SVS_RESPCODE_INVALID_HANDLE        = 17,
    SVS_RESPCODE_NOTREACH_CLIENT       = 18,
    SVS_RESPCODE_SCHEDULE_RESET        = 19,
    SVS_RESPCODE_NO_VIDIO_ROUTER       = 20,
    SVS_RESPCODE_NOT_REACH_SCHEDULE    = 21,
    SVS_RESPCODE_UPDATE_CLIENT         = 22,
    SVS_RESPCODE_CANT_CONNECT_VTDU     = 23,
    SVS_RESPCODE_GOT_ROUTER            = 24,
    SVS_RESPCODE_NOTREACH_VTDU         = 25,
    SVS_RESPCODE_NOTREACH_FRONTSVR     = 26,
    SVS_RESPCODE_SERVER_DISCONNECT     = 27,
    SVS_RESPCODE_NOT_UPLOADING_DEV     = 28,
    SVS_RESPCODE_UPLOADING_FILE        = 29,
    SVS_RESPCODE_NOT_REACH_RECORDSVR   = 30,
    SVS_RESPCODE_NO_EVENT_STRATEGY     = 31,
    SVS_RESPCODE_NO_STORE_SERVER       = 32,
    SVS_RESPCODE_OVERLOAD              = 33,
    SVS_RESPCODE_TOO_MANY_RECORDS      = 34,
    SVS_RESPCODE_MSG_TOO_LONG          = 35,
    SVS_RESPCODE_SYSTEM_BUSY           = 36,

    SVS_RESPCODE_LAYER_MAX             = 37,
    SVS_RESPCODE_CHANNEL_MAX           = 38,
    SVS_RESPCODE_PLAYBACK_MAX          = 80,
    SVS_RESPCODE_OTHER_ERROR           = 88,
    SVS_RESPCODE_COUNT,

    SVS_RESPCODE_USER_MAX               = 100,
    SVS_RESPCODE_USER_EXIST             = 101,
    SVS_RESPCODE_USER_NOEXIST           = 102,
    SVS_RESPCODE_DOMAIN_MAXSESSION      = 103,

    SVS_RESPCODE_NO_BUSS_AUTH          = 104,
    SVS_RESPCODE_PU_NEED_UPDATE        = 105,
    SVS_RESPCODE_DEVICE_OFFLINE        = 106,

    SVS_RESPCODE_PU_IS_UPGRADING       = 107,

    SVS_RESPCODE_EXCEED_MAX_DEVICE_NUM_PER_STRATEGY   = 120,

    SVS_RESPCODE_DEVICE_HAVE_NO_BINDED_NRU    = 130,

    SVS_RESPCODE_UPGRADE_TASK_ALREADY_FINISHED   = 131,
    SVS_RESPCODE_UPDATE_UPGRADE_TASK_STATUS_FAIL = 132,

    SVS_RESPCODE_DB_ERR                  = 800,
    SVS_RESPCODE_DEVNOREGIST_FRONTSVR  =801,
    SVS_RESPCODE_STRATEGYNUM_OVERLOAD      =802,

    SVS_RESPCODE_STRATEGY_NOTEXIST = 803,

    SVS_RESPCODE_FRONT_PLAYBACK_ALREADY_EXIST = 804,

    SVS_RESPCODE_READ_PMSCFG_ERROR = 900,
    SVS_RESPCODE_DSGW_NOT_EXIST_ERROR = 1000,
    SVS_RESPCODE_INVALID_CONSOLEID_ERROR = 1001,
    SVS_RESPCODE_HAVE_NO_RIGHT_TO_CAMERA        = 1002,
    SVS_RESPCODE_HAVE_NO_RIGHT_TO_MONITOR       = 1003,
    SVS_RESPCODE_MATRIX_ABNORMAL                = 1004,
    SVS_RESPCODE_CAMERA_ABNORMAL                = 1005,
    SVS_RESPCODE_PTZ_IN_USE                     = 1006,
    SVS_RESPCODE_PTZ_PHYSICS_CONNECTION_ERROR   = 1007,
    SVS_RESPCODE_TIMEOUT                        = 1008,
    SVS_RESPCODE_UNSUPPORTED_PTZ_OPERATION      = 1009,
    SVS_RESPCODE_INVALID_PARAMETER              = 1010,
    SVS_RESPCODE_CONSOLE_NOT_REGISTERED         = 1011,
    SVS_RESPCODE_ASGW_OFFLINE                   = 1012,

    ERROR_SYS                       = 0x1101,
    ERROR_SVS_SYSADMIN_SVR          = 0x1120,
    ERROR_SVS_BUSINESS_SVR,
    ERROR_SVS_CONTROL_SVR,
    ERROR_SVS_ALARM_SVR,
    ERROR_SVS_SCHEDULE_SVR,
    ERROR_SVS_STORE_SVR,
    ERROR_VTDU_SVR,
    ERROR_LARGE_DATA,

    SVS_RESPCODE_UPGRADETASK_ALREADY_INITED    = 0x3000,
    SVS_RESPCODE_DBAPI_POINTER_NULL            = 0x3001,
    SVS_RESPCODE_REACTOR_INSTANCE_POINTER_NULL = 0x3002,
    SVS_RESPCODE_ALLOC_TIMER_MANAGER_FAILED    = 0x3003,
    SVS_RESPCODE_INIT_TIMER_MANAGER_FAILED     = 0x3004,
    SVS_RESPCODE_UPGRADETASK_NOT_EXIST         = 0x3005,
    SVS_RESPCODE_UPGRADETASK_EXISTED           = 0x3006,
    SVS_RESPCODE_MSG_LEN_INVALID               = 0x3007,
    SVS_RESPCODE_ALLOC_MEMORY_FAILED           = 0x3008,
    SVS_RESPCODE_SYSADMIN_PU_IS_UPGRADING      = 0x3009,
    SVS_RESPCODE_SYNC_USER_EXCEED_MAX          = 0x300A,

    SVS_RESPCODE_LENS_STRATEGY_INVALID = 0x7000,
    SVS_RESPCODE_LENS_DISTRIBUTE_TYPE_INVALID = 0x7001,
    SVS_RESPCODE_LENS_DISTRIBUTE_INNER_ERROR = 0x7002,

};

#define SVS_ERROR_OK                       0
#define SVS_ERROR_FAIL                    -1

#define SVS_ERROR_USER_NO_EXIST           0x0001

#endif //_SVS_RC_H


